// Template categories
export const templateCategories = [
  { id: 'all', name: 'All Templates' },
  { id: 'ai', name: 'AI & Machine Learning' },
  { id: 'customer-support', name: 'Customer Support' },
  { id: 'marketing', name: 'Marketing' },
  { id: 'sales', name: 'Sales' },
  { id: 'data', name: 'Data Processing' },
  { id: 'engineering', name: 'Engineering' },
  { id: 'product', name: 'Product' },
  { id: 'personal', name: 'Personal' },
];

// Templates data
export const templatesData = [
  {
    id: 'seo-blog',
    emoji: '📝',
    title: 'AI-Powered SEO Blog Generator',
    description: 'Automate the creation of SEO-optimized blog posts using AI and NLP',
    category: 'marketing',
    backgroundColor: '#10b981',
  },
  {
    id: 'perplexity',
    emoji: '🌐',
    title: 'Perplexity Clone',
    description: 'This workflow searches the web and uses an LLM to format a response',
    category: 'ai',
    backgroundColor: '#4f46e5',
  },
  {
    id: 'basic-llm',
    emoji: '🚀',
    title: 'Basic LLM Workflow',
    description: 'Enhance your productivity with the Basic LLM Workflow',
    category: 'ai',
    backgroundColor: '#b91c1c',
  },
  {
    id: 'slack-rag',
    emoji: '💬',
    title: 'AI Slack RAG Bot (Simple)',
    description: 'This workflow is the second part of a two-part system',
    category: 'customer-support',
    backgroundColor: '#7c3aed',
  },
  {
    id: 'rag',
    emoji: '📊',
    title: 'Basic RAG Workflow',
    description: "A basic RAG workflow template using Scout's powerful workflow builder",
    category: 'ai',
    backgroundColor: '#db2777',
  },
  {
    id: 'model-comparison',
    emoji: '⚖️',
    title: 'LLM Model Comparison Tool',
    description: 'Compare the performance, cost, and output of multiple AI language models',
    category: 'ai',
    backgroundColor: '#059669',
  },
  {
    id: 'email-generator',
    emoji: '📧',
    title: 'AI Email Generator',
    description: 'Generate professional emails with customizable templates and tone',
    category: 'marketing',
    backgroundColor: '#d97706',
  },
  {
    id: 'data-analysis',
    emoji: '📈',
    title: 'Data Analysis Pipeline',
    description: 'Process and analyze data from multiple sources',
    category: 'data',
    backgroundColor: '#0ea5e9',
  },
  {
    id: 'customer-service',
    emoji: '🎭',
    title: 'Customer Service Agent',
    description: 'AI-powered customer service agent workflow',
    category: 'customer-support',
    backgroundColor: '#8b5cf6',
  },
];
